version: 2
updates:
  - package-ecosystem: "docker"
    directory: "." 
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "docker.io/library/golang"
      - dependency-name: "docker.io/library/gradle"