name: "Auto Draft Release"
on:
  pull_request:
    types:
      - closed

jobs:
  draft-release:
    if: github.event.pull_request.merged == true
    name: "Draft Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: "softprops/action-gh-release@v1"
        with:
          token: ${{ steps.generate-token.outputs.token }}
          draft: true
          tag_name: 'latest'
          prerelease: true
          name: 'Latest Mautrix-Signal'
          generate_release_notes: true
