name: "Auto Draft Release"
on:
  pull_request:
    types:
      - closed

jobs:
  draft-release:
    if: github.event.pull_request.merged == true
    name: "Draft Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ steps.generate-token.outputs.token }}
          draft: true
          automatic_release_tag: 'latest'
          prerelease: false
